export const desktopIcons: DesktopIcons[] = [
  {
    id: "readme",
    type: "readme",
    label: "README.txt",
    icon: "icons/readme.png",
    size: "900x800",
  },
  {
    id: "projects",
    type: "folder",
    label: "Projects",
    icon: "icons/folder.png",
    children: [
      {
        id: "webDevelopment",
        type: "folder",
        label: "Web Development",
        icon: "icons/folder.png",
        children: [
          {
            id: "simplefeedback",
            type: "project",
            label: "Simple Feedback",
            icon: "icons/simplefeedback.png",
            size: "fullscreen",
          },
          {
            id: "tobiOS",
            type: "project",
            label: "TobiOS",
            icon: "icons/windows.png",
            size: "fullscreen",
          },
          {
            id: "kitzEdu",
            type: "project",
            label: "Kitz-Edu 2.0",
            icon: "icons/kitzedu.png",
            size: "fullscreen",
          },
          {
            id: "betterSpotify",
            type: "project",
            label: "Better Spotify",
            icon: "icons/spotify.png",
            size: "fullscreen",
          },
          {
            id: "odin",
            type: "project",
            label: "Odin",
            icon: "icons/odin.png",
            size: "fullscreen",
          },
          {
            id: "smallerProjects",
            type: "folder",
            label: "Smaller Projects",
            icon: "icons/folder.png",
            children: [
              /*{
                id: "IMCMguide",
                type: "project",
                label: "IMCM Guide",
                icon: "icons/guidebook.png",
                size: "fullscreen",
              },*/
              {
                id: "libraryProject",
                type: "iframe",
                label: "Library",
                icon: "icons/bookshelf.png",
                link: "https://tobiashain.github.io/Odin-Project/Library/",
                size: "900x800",
              },
              {
                id: "battleShipProject",
                type: "iframe",
                label: "Battleship",
                icon: "icons/battleship.png",
                link: "https://tobiashain.github.io/Odin-Project/Battleship/",
                size: "1300x800",
              },
              {
                id: "weatherProject",
                type: "iframe",
                label: "Weather",
                icon: "icons/weather.png",
                link: "https://tobiashain.github.io/Odin-Project/Weather/",
                size: "400x500",
              },
              {
                id: "calculatorProject",
                type: "iframe",
                label: "Calculator",
                icon: "icons/calculator.png",
                link: "https://tobiashain.github.io/Odin-Project/Calculator/",
                size: "600x600",
              },
            ],
          },
        ],
      },
      {
        id: "softwareDevelopment",
        type: "folder",
        label: "Software Development",
        icon: "icons/folder.png",
        children: [
          {
            id: "skyfallow",
            type: "project",
            label: "Skyfallow",
            icon: "icons/controller.png",
            size: "fullscreen",
          },
          {
            id: "untitledPlatformer",
            type: "project",
            label: "Untitled 3D Platformer",
            icon: "icons/controller.png",
            size: "fullscreen",
          },
          {
            id: "unserLagerhaus",
            type: "project",
            label: "Unser Lagerhaus",
            icon: "icons/task.png",
            size: "fullscreen",
          },
          {
            id: "minesweeper",
            type: "project",
            label: "Minesweeper",
            icon: "icons/mine.png",
            size: "fullscreen",
          },
          {
            id: "snake",
            type: "project",
            label: "Snake",
            icon: "icons/snake.png",
            size: "fullscreen",
          },
        ],
      },
    ],
  },
  {
    id: "portfolio",
    type: "iframe",
    label: "Portfolio",
    icon: "icons/browser.png",
    link: "https://tobiashain.github.io/",
    size: "fullscreen",
  },
  {
    id: "github",
    type: "link",
    label: "Github",
    icon: "icons/github.png",
    link: "https://github.com/tobiashain",
  },
  {
    id: "email",
    type: "link",
    label: "Email",
    icon: "icons/email.png",
    link: "mailto:hain.tobias@outlook.at",
  },
  {
    id: "wired",
    type: "wired",
    label: "The Wired",
    icon: "icons/wired.png",
  },
  {
    id: "lain",
    type: "video",
    label: "Let's All Love Lain",
    icon: "icons/loveLain.png",
    link: "T0xCK6J1ics",
  },
  {
    id: "games",
    type: "folder",
    label: "Games",
    icon: "icons/folder.png",
    children: [
      {
        id: "battleShip",
        type: "iframe",
        label: "Battleship",
        icon: "icons/battleship.png",
        link: "https://tobiashain.github.io/Odin-Project/Battleship/",
        size: "1300x800",
      },
      {
        id: "tictactoe",
        type: "iframe",
        label: "Tic Tac Toe",
        icon: "icons/controller.png",
        link: "https://tobiashain.github.io/Odin-Project/Tic-Tac-Toe/",
        size: "800x800",
      },
      {
        id: "rockPaperScissor",
        type: "iframe",
        label: "Rock Paper Scissor",
        icon: "icons/controller.png",
        link: "https://tobiashain.github.io/Odin-Project/Rock-Paper-Scissors/",
        size: "300x300",
      },
      {
        id: "etchASketch",
        type: "iframe",
        label: "Etch A Sketch",
        icon: "icons/controller.png",
        link: "https://tobiashain.github.io/Odin-Project/Etch-a-Sketch/",
        size: "600x600",
      },
    ],
  },
  {
    id: "calculator",
    type: "iframe",
    label: "Calculator",
    icon: "icons/calculator.png",
    link: "https://tobiashain.github.io/Odin-Project/Calculator/",
    size: "600x600",
  },
  {
    id: "library",
    type: "iframe",
    label: "Library",
    icon: "icons/bookshelf.png",
    link: "https://tobiashain.github.io/Odin-Project/Library/",
    size: "900x800",
  },
  {
    id: "weather",
    type: "iframe",
    label: "Weather",
    icon: "icons/weather.png",
    link: "https://tobiashain.github.io/Odin-Project/Weather/",
    size: "400x500",
  },
  {
    id: "todoList",
    type: "iframe",
    label: "Todo App",
    icon: "icons/note.png",
    link: "https://tobiashain.github.io/Odin-Project/Todo-List/",
    size: "fullscreen",
  },
  {
    id: "music",
    type: "music",
    label: "Music",
    icon: "icons/music.png",
    size: "800x500",
  },
];

export interface DesktopIcons {
  id: string;
  type: string;
  label: string;
  icon: string;
  children?: DesktopIcons[];
  link?: string;
  size?: string;
}
