export interface Project {
  id: string;
  title: string;
  subTitle: string;
  context: string;
  chips: string[];
  features: string[];
  images: string[];
  website?: string;
  sourceCode?: string;
}

export const projects: Project[] = [
  {
    id: "simplefeedback",
    title: "Simplefeedback",
    subTitle: "Customer-Relationship-Management Platform",
    context:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
    chips: [
      "React",
      "JavaScript",
      "TypeScript",
      "Sass",
      "MySQL",
      "NestJS",
      "Knex.js",
      "Docker",
      "Stripe",
      "Github Actions",
      "Google Cloud Storage",
      "Google OAuth 2.0",
    ],
    features: [
      "Create Surveys",
      "Stripe payment processing integration",
      "Data visualization via Diagrams",
      "HTML Email Builder",
      "Send Newsletters",
    ],
    images: [
      "/TobiOS/pictures/simplefeedback/1.png",
      "/TobiOS/pictures/simplefeedback/2.png",
      "/TobiOS/pictures/simplefeedback/3.png",
      "/TobiOS/pictures/simplefeedback/4.png",
    ],
    website: "https://simplefeedback.de/",
  },
  {
    id: "tobiOS",
    title: "",
    subTitle: "",
    context: "",
    chips: [
      "React",
      "JavaScript",
      "TypeScript",
      "Sass",
      "interact.js",
      "Github Actions",
      "Cloudflare Workers",
    ],
    features: ["SQL"],
    images: [],
    website: "https://example.com/",
    sourceCode: "https://example.com/",
  },
  {
    id: "kitzEdu",
    title: "",
    subTitle: "",
    context: "",
    chips: ["Next.js", "Strapi", "JavaScript", "Sass"],
    features: [],
    images: [
      "/TobiOS/pictures/kitz-edu/1.png",
      "/TobiOS/pictures/kitz-edu/2.png",
      "/TobiOS/pictures/kitz-edu/3.png",
      "/TobiOS/pictures/kitz-edu/4.png",
    ],
    sourceCode: "https://example.com/",
  },
  {
    id: "betterSpotify",
    title: "",
    subTitle: "",
    context: "",
    chips: ["ASP.Net MVC", "C#", "JavaScript", "TailwindCSS", "Spotify API"],
    features: [],
    images: [],
    sourceCode: "https://example.com/",
  },
  {
    id: "todoApp",
    title: "",
    subTitle: "",
    context: "",
    chips: ["JavaScript", "TypeScript", "Sass"],
    features: [],
    images: [],
    website: "https://example.com/",
    sourceCode: "https://example.com/",
  },
  {
    id: "wordpress",
    title: "",
    subTitle: "",
    context: "",
    chips: ["Wordpress", "Elementor"],
    features: [],
    images: [],
  },
  {
    id: "IMCMguide",
    title: "",
    subTitle: "",
    context: "",
    chips: ["PHP", "JavaScript", "CSS"],
    features: [],
    images: [],
  },
  {
    id: "skyfallow",
    title: "",
    subTitle: "",
    context: "",
    chips: ["Godot", "GDScript", "C#"],
    features: [],
    images: [],
  },
  {
    id: "untitledPlatformer",
    title: "",
    subTitle: "",
    context: "",
    chips: ["Unity", "C#"],
    features: [],
    images: [],
  },
  {
    id: "unserLagerhaus",
    title: "",
    subTitle: "",
    context: "",
    chips: ["C#", "MySQL", "Windows Forms"],
    features: [],
    images: [],
  },
  {
    id: "minesweeper",
    title: "",
    subTitle: "",
    context: "",
    chips: ["C#", "Windows Forms"],
    features: [],
    images: [],
  },
  {
    id: "snake",
    title: "",
    subTitle: "",
    context: "",
    chips: ["C#", "Raylib"],
    features: [],
    images: [],
  },
];
